#1160 show decision description improvement
openmsupply/conforma-web-app pull request #1282
Opened 2022-08-11 05:35 UTC by nmadruga

fixes #1160

**In progress**

Adding description for each type of decision inline with the decision. Currently just showing when the decision is selected. Opinions @jagoje @CarlosNZ @fergie-nz ?
![Screen Shot 2022-08-11 at 5 35 08 PM](https://user-images.githubusercontent.com/16461988/184070280-59dce100-a776-45c2-b2b1-a86a03ec0b3c.png)
![Screen Shot 2022-08-11 at 5 34 56 PM](https://user-images.githubusercontent.com/16461988/184070285-40b0457d-18a9-4e5c-8e70-1bca31334e71.png)

2022-08-11 05:44 UTC, CarlosNZ commented
Is the purpose of this just to show an explanation of what each option does?

If so, couple of ideas:
- the most obvious thing seems to change the actual text to something more appropriate. Like "Conform" should just be "Approve", no need for both. 
- if we still need more info, this seems like a good use for a tool-tip or popover: https://react.semantic-ui.com/modules/popup/ rather than cluttering the UI. 
- we're not going to show the actual list of questions are we? Cos that's already in the the Preview.

2022-08-12 03:14 UTC, CarlosNZ requested changes
That's great, works really well and does what it needs to without being intrusive.

We should think about other places this component would be useful.

General comments:
- Might be time to move "Tooltip", and the "Loading"/"NoMatch" components into a subfolder called "Common"?
- I think the icon could do with some styling. Not sure exactly what, but I think this makes it look a bit more like a "typical" tooltip icon:
  -  icon to "help circle" (I'd be inclined to make the icon an (optional) prop, but can do that when we need something different)
  - color: grey (more subtle)
  - margin (on both sides) so it's not so close to the text

See inline comments for more.

2022-08-12 03:16 UTC, CarlosNZ commented on src/components/Review/ReviewComment.tsx
> +        <Tooltip message={strings.LABEL_REVIEW_OVERALL_COMMENT_TOOLTIP} />
I think setting a max-width of around 500 looks better for this one in particular:
![Screen Shot 2022-08-12 at 2 59 43 PM](https://user-images.githubusercontent.com/5456533/184276956-4c86797f-4290-47b8-9baf-c4f9ef721061.png)

Probably should add a few basic style props to this component cos different cases would want different widths.

You probably want at least:
- min-width
- max-width

Make sure they have defaults though (probably 500px for max-width, and just let the Popup component use its own min-width)

2022-08-12 03:18 UTC, CarlosNZ commented
> * I think the icon could do with some styling. Not sure exactly what, but I think this makes it look a bit more like a "typical" tooltip icon:

Speaking of "typical" tooltip, I just noticed the Github one right here on this page!
![Screen Shot 2022-08-12 at 3 15 26 PM](https://user-images.githubusercontent.com/5456533/184278766-54ed9730-215a-4e63-bb8c-fc8faf581fe4.png)

I think the question mark is fine, but overall this one looks pretty good and is kind of what I'm thinking of in my comments above.

2022-08-14 23:29 UTC, CarlosNZ commented
Here's my suggested changes all in one comparison: https://github.com/openmsupply/conforma-web-app/compare/%231160-show-decision-description-improvement...%231160-show-decision-description-style-tweaks

Please merge into here if you're happy with it. Basically just makes layout a little tidier and made "Tooltip" component more generic (but with defaults) for future re-use.

2022-08-15 00:05 UTC, nmadruga commented
All good for me, Carl. Can this be merged?

2022-08-15 00:20 UTC, CarlosNZ approved these changes
👍

Looking good :)

2022-08-15 02:54 UTC, merged