#1299 Assign reviewer to all levels at once
openmsupply/conforma-web-app pull request #1319
Opened 2022-08-29 21:20 UTC by CarlosNZ

Fix #1299 

![Screen Shot 2022-08-30 at 9 16 44 AM](https://user-images.githubusercontent.com/5456533/187300838-efcc0fa5-2b87-4fd6-8a66-3427ce7c71c8.png)

Adds dropdown to select a reviewer to "assign all" to. It only assigns sections that are:
- allowed to be assigned to that reviewer
- not already assigned

There is a Tooltip info icon which explains this to the user.

Only shows when it's *not* last level, as last level is already assigned to all.

I've tried to account for as many review/assignment states as I can, but please see if there's any that I've missed.

I was testing with the same "Optional Review testing" snapshot (in templates repo) that I used for my last PR, so use that one if you want to quickly go through an application/review process.

2022-08-29 21:26 UTC, CarlosNZ commented on src/components/Tooltip.tsx
> +  iconStyle,
I realised that the current `style` prop only applied to the pop itself, not the icon. Now we can discriminate between them.

2022-08-29 21:26 UTC, CarlosNZ commented on src/containers/Review/assignment/AssignAll.tsx
> +        iconStyle={{ height: '1.4em' }}
Not sure why this was necessary, but it doesn't center-align vertically without this.

2022-08-29 22:13 UTC, CarlosNZ commented on semantic/src/site/globals/site.overrides
> +    margin-bottom: 60px; // to offset the Actions area that covers it.
This is to make the scrolling work properly for Preview modal. I thought I'd already fixed this, but I hadn't allowed for the height of the "Actions" area at the bottom (with the OK button), which covers the main content.

The actions area is absolutely positioned, so the main content sits behind it and doesn't show a scroll bar until it's taller than the whole preview area, including the area covered by the actions area. This extra margin is the height of the actions area, so content won't get stuck behind it without a scroll bar.

2022-08-30 01:48 UTC, nmadruga commented
> **Update**: there's a small unrelated fix for scrolling in the Preview window. See inline comment for details.

Cool. Should this be a good moment to also add this improvement? #1313

2022-08-30 02:07 UTC, nmadruga requested changes
The code looks good - I haven't seen anything that requires changes. Although while testing (with our latest snapshot) I found an issue. I think we do allow the `ReviewAssignment.allowSections` to be Null in case all sections are allowed. And in that case the function `getReviewerList` is returning empty array. So we don't have the **AssignAll** component displaying.

2022-08-30 03:10 UTC, CarlosNZ commented
> Cool. Should this be a good moment to also add this improvement? #1313

Sure -- this should fix #1313 4663a17f

2022-08-30 03:10 UTC, CarlosNZ commented
> The code looks good - I haven't seen anything that requires changes. Although while testing (with our latest snapshot) I found an issue. I think we do allow the `ReviewAssignment.allowSections` to be Null in case all sections are allowed. And in that case the function `getReviewerList` is returning empty array. So we don't have the **AssignAll** component displaying.

Okay, have removed the additional filter, as we discussed in person, and added a comment to the commented-out line. 4663a17f

2022-08-30 03:35 UTC, nmadruga approved these changes

2022-08-30 03:37 UTC, merged