#1508 listBuidler layout improvements
openmsupply/conforma-web-app pull request #1509
Opened 2023-05-18 03:20 UTC by CarlosNZ

Fix #1508 

Two new parameters for listBuilder:
- `inlineOpen` -- specify whether the Accordions should appear already open (not collapsed) for "inline" view elements
- `tableExcludeColumns` -- specify columns to hide in Table view (to prevent too much clutter when there are lots of fields)

2023-05-18 03:22 UTC, CarlosNZ commented on docs/internal/Element-Type-Specs.md
> +![style:warning](images/Element-Type-Specs-textInfo-warning.png)
This URL syntax was preventing the images showing up on the wiki. Hopefully this fixes it.

2023-05-18 03:22 UTC, CarlosNZ commented on src/formElementPlugins/listBuilder/src/types.ts
> +  inputFields: TemplateElement[]
Stricter type here means less "as" etc inside. ;)

2023-06-28 04:27 UTC, fergie-nz requested changes
I'm getting funny rendering effects when inlineOpen set to true - 

This is an example from the Provisional Medicinal Product Registration from Fiji

2023-06-28 04:30 UTC, CarlosNZ commented
> This is an example from the Provisional Medicinal Product Registration from Fiji

That's for the "Search" element *within* the listBuilder, not the listBuilder itself. It shouldn't affect it, but it's weird. I'll take a look.

2023-06-29 23:26 UTC, fergie-nz approved these changes
Nice have it working with newer snapshot

2023-06-29 23:40 UTC, merged